window.SLASH_CMDS = [
  { name: 'always-approve', desc: '切换始终批准模式（跳过所有权限确认）' },
  { name: 'announcements', desc: '显示或隐藏公告' },
  { name: 'auto', desc: '切换自动模式（分类器批准安全工具）' },
  { name: 'btw', desc: '旁问一句，不打断当前回合' },
  { name: 'cd', desc: '更改新代理的工作目录' },
  { name: 'compact', desc: '压缩对话历史' },
  { name: 'compact-mode', desc: '切换紧凑界面（更少边距、更多内容）' },
  { name: 'config-agents', desc: '管理代理定义' },
  { name: 'context', desc: '查看上下文占用' },
  { name: 'copy', desc: '复制最近一条回复到剪贴板（/copy N 复制第 N 条）' },
  { name: 'debug', desc: '切换调试叠加层' },
  { name: 'docs', desc: '打开操作指南或在线 Build 文档' },
  { name: 'effort', desc: '设置当前模型的推理强度' },
  { name: 'expand', desc: '重新完整展开上一个折叠块（精简模式）' },
  { name: 'export', desc: '导出当前对话到文件或剪贴板' },
  { name: 'feedback', desc: '发送关于当前会话的反馈' },
  { name: 'find', desc: '搜索对话回滚内容' },
  { name: 'fork', desc: '将当前会话分支为对等代理' },
  { name: 'gboom', desc: '隐藏彩蛋' },
  { name: 'help', desc: '浏览命令与键盘快捷键' },
  { name: 'history', desc: '搜索输入历史' },
  { name: 'home', desc: '返回欢迎页' },
  { name: 'import-claude', desc: '打开 Claude 设置导入窗口' },
  { name: 'login', desc: '登录或重新认证账号' },
  { name: 'logout', desc: '登出并返回登录页' },
  { name: 'loop', desc: '按间隔循环运行提示' },
  { name: 'mcps', desc: '显示 MCP 服务器状态' },
  { name: 'model', desc: '切换当前模型' },
  { name: 'multiline', desc: '切换多行输入（交换 Enter 与 Shift+Enter）' },
  { name: 'new', desc: '开始新会话' },
  { name: 'personas', desc: '管理角色（创建、编辑、删除）' },
  { name: 'plan', desc: '进入计划模式' },
  { name: 'privacy', desc: '查看或切换隐私与数据保留状态' },
  { name: 'queue', desc: '列出当前回合后排队的提示' },
  { name: 'quit', desc: '退出应用' },
  { name: 'recap', desc: '总结目前会话' },
  { name: 'release-notes', desc: '查看当前版本更新说明' },
  { name: 'remember', desc: '保存一条记忆' },
  { name: 'rename', desc: '重命名当前会话' },
  { name: 'resume', desc: '恢复历史会话' },
  { name: 'rewind', desc: '回退到之前的回合' },
  { name: 'scroll-debug', desc: '切换滚动诊断 HUD' },
  { name: 'session-info', desc: '显示会话信息' },
  { name: 'settings', desc: '打开设置' },
  { name: 'share', desc: '通过 URL 分享本会话' },
  { name: 'skills', desc: '查看技能' },
  { name: 'tasks', desc: '列出后台任务、子代理与定时任务' },
  { name: 'terminal-setup', desc: '检查终端、颜色与剪贴板设置' },
  { name: 'theme', desc: '切换配色主题' },
  { name: 'timestamps', desc: '开关消息时间戳' },
  { name: 'toggle-mouse-reporting', desc: '切换终端鼠标上报（原生拖选复制粘贴）' },
  { name: 'transcript', desc: '在系统分页器中查看完整对话记录' },
  { name: 'usage', desc: '查看额度或管理账单' },
  { name: 'view-plan', desc: '查看当前计划' },
  { name: 'vim-mode', desc: '切换 vim 风格回滚快捷键（j/k、h/l、g/G、y/Y…）' },
];
